import { BROWSER_PROTOCOL_SCHEMA_VERSION, getNativeMethodSchemaCatalog, NATIVE_METHOD_SCHEMA_CATALOG_VERSION } from './browserProtocolSchemas.js';
import {
  TARGET_NATIVE_INVALID_RESPONSE_ERROR,
  TARGET_NATIVE_RESPONSE_HANDLING,
  XWOW_NATIVE_RESPONSE_VALIDATION,
} from './nativeTransport.js';
import {
  TARGET_UNKNOWN_NATIVE_METHOD_ERROR_CODE,
  TARGET_UNSUPPORTED_COMMAND_ERROR_CODE,
  TARGET_UNSUPPORTED_COMMAND_MESSAGE_TEMPLATE,
  XWOW_UNKNOWN_NATIVE_METHOD_ERROR_CODE,
} from './unsupportedCommandRuntime.js';

export const PLUGIN_CAPABILITIES = [
  'page.read',
  'page.readFrames',
  'page.extractData',
  'page.scrollTrack',
  'page.clickElement',
  'page.hoverElement',
  'page.clickPagination',
  'page.selectElement',
  'page.typeElement',
  'page.waitStable',
  'page.waitForSelector',
  'page.checkElement',
  'page.isCheckedElement',
  'page.isVisibleElement',
  'page.getElementValue',
  'page.getElementAttribute',
  'page.queryElements',
  'page.clipboard',
  'page.fileChooser',
  'page.consoleLogs',
  'page.screenshot',
  'page.downloadWait',
  'browser.downloadWait',
  'browser.downloadState',
  'browser.sessionLease',
  'browser.tabLeaseSnapshot',
  'browser.sessionTabs',
  'browser.sessionActiveRequests',
  'browser.sessionInMemoryRuntime',
  'browser.sessionTurnHandoff',
  'browser.managedTabGroups',
  'browser.tabLifecycle',
  'browser.tabLifecycleEvents',
  'browser.windowSnapshot',
  'browser.visibility',
  'browser.pageNavigation',
  'browser.pageReadiness',
  'browser.frameSnapshot',
  'browser.webMcp',
  'browser.pageScroll',
  'browser.pageClick',
  'browser.pageHover',
  'browser.pageType',
  'browser.pagePointInspection',
  'browser.pageSelectorWait',
  'browser.pageCheckControl',
  'browser.pageCheckState',
  'browser.pageElementState',
  'browser.pageElementValue',
  'browser.pageElementAttributes',
  'browser.pageDomSnapshot',
  'browser.pageExport',
  'browser.urlContent',
  'browser.pageScript',
  'browser.pageClipboard',
  'browser.pageFileChooser',
  'browser.pageConsoleLogs',
  'browser.pageSelect',
  'browser.activeTabObserver',
  'browser.tabStateRepublish',
  'browser.actionPolicy',
  'browser.approvalTokenPolicy',
  'browser.capabilityDiscovery',
  'browser.protocolSchemas',
  'browser.unsupportedCommandFallback',
  'browser.viewport',
  'browser.cdp',
  'browser.cdpPageRuntime',
  'browser.cdpEvents',
  'browser.pixelInput',
  'browser.history',
  'browser.bookmarks',
  'browser.topSites',
  'browser.readingList',
  'browser.sessions',
  'browser.userContext',
  'browser.targetList',
  'browser.nativeMessaging',
  'browser.eventBridge',
  'browser.eventLog',
  'browser.eventReplay',
  'browser.eventSummary',
  'browser.sessionEvents',
  'browser.lifecycleGuard',
  'browser.sidePanelStatus',
  'browser.sidePanelControl',
  'browser.finalizedTabBadges',
  'page.assetInventory',
  'page.assetBundle',
  'siteRules.adapterRegistry',
  'scraper.saveTemplate',
  'scraper.preview',
  'scraper.run',
  'scraper.bulkUrls',
  'app.commandPoll',
  'app.captureIngest',
  'app.aiExtract',
];

export const CAPABILITY_CONTRACT_SCHEMA_VERSION = 1;

export const CAPABILITY_CONTRACTS = {
  'browser.info': capabilityContract('browser.info', {
    action: 'browser.info',
    actionClass: 'observe',
    summary: 'Return extension, browser-control, user-state, event, and permission metadata.',
  }),
  'browser.capabilityDiscovery': capabilityContract('browser.capabilityDiscovery', {
    actions: ['browser.capabilities', 'capabilities.get', 'getCapabilities'],
    actionClass: 'observe',
    outputSchemaVersion: 1,
    summary: 'Return the same capability contracts and schema versions as browser.info through a narrow discovery action.',
  }),
  'browser.eventSummary': capabilityContract('browser.eventSummary', {
    actions: ['browser.events.summary', 'events.summary', 'getBrowserEventSummary'],
    actionClass: 'observe',
    filters: ['eventType', 'sessionId', 'turnId', 'bridgeMethod', 'since', 'afterEventId'],
    outputFields: ['total', 'newestEventId', 'oldestEventId', 'byEventType', 'bySourceKind', 'nativeDelivery', 'checkpoint'],
    checkpointSchemaVersion: 1,
    checkpointFields: ['latestByEventType', 'latestBySourceKind', 'nextQuery.afterEventId', 'nextQuery.since'],
    nativeDeliveryFields: ['posted', 'success', 'pending', 'failed'],
    replayPlan: ['call browser.events.summary on reconnect', 'compare newestEventId/newestEmittedAt/counts', 'call browser.events with afterEventId or since when changed'],
    targetBoundary: 'target_confirms_native_event_push; xwow_adds_bounded_replay_summary',
    outputSchemaVersion: 1,
    summary: 'Return bounded event counts, native delivery totals, and reconnect checkpoint cursors for missed-event reconciliation without pulling full event bodies.',
  }),
  'browser.sessionEvents': capabilityContract('browser.sessionEvents', {
    action: 'browser.sessionEvents',
    actionClass: 'observe',
    filters: ['eventType', 'sessionId', 'turnId', 'limit'],
    summary: 'Replay browser-control session lifecycle events.',
  }),
  'browser.downloadState': capabilityContract('browser.downloadState', {
    actions: ['download.state', 'downloads.state', 'getDownloadState'],
    actionClass: 'observe',
    outputSchemaVersion: 1,
    summary: 'Return target-style download id indexes for filename, URL, status, and operator context without replaying event bodies.',
  }),
  'browser.downloadWait': capabilityContract('browser.downloadWait', {
    actions: ['download.wait'],
    actionClass: 'read_only_export',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    bindings: ['download_id', 'timeout_ms', 'tabId', 'sessionId', 'turnId'],
    targetFields: ['download_id', 'path'],
    xwowExtensionFields: ['urlContains', 'filenameContains', 'artifactBinding', 'downloadContext', 'waitId'],
    summary: 'Wait for a target-style download id and return the resolved local path while preserving XWOW artifact reconciliation metadata.',
  }),
  'browser.tabLifecycle': capabilityContract('browser.tabLifecycle', {
    actions: ['tab.create', 'createTab', 'window.create', 'browser.windowCreate', 'createWindow', 'tab.claim', 'tab.activate', 'activateTab', 'focusTab', 'tab.navigate', 'navigateTab', 'tab.reload', 'reloadTab', 'tab.close', 'tab.remove', 'closeTab', 'tabs.finalize', 'finalizeTabs'],
    actionClass: 'state_changing',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    bindings: ['actionType', 'sessionId', 'tabId'],
    summary: 'Create controlled tabs/windows, claim, close, finalize, and release controlled browser tabs through the session lease runtime.',
  }),
  'browser.tabLifecycleEvents': capabilityContract('browser.tabLifecycleEvents', {
    actions: ['tab.lifecycleEvents', 'tabs.lifecycleEvents', 'tabLifecycle.events', 'getTabLifecycleEvents', 'tab.lifecycleSnapshot', 'tabs.lifecycleSnapshot', 'tabLifecycle.snapshot', 'getTabLifecycleSnapshot'],
    actionClass: 'observe',
    outputSchemaVersion: 1,
    filters: ['kind', 'tabId', 'windowId', 'since', 'afterEventId', 'limit'],
    summary: 'Replay Chrome tab/window lifecycle events and return a bounded lifecycle snapshot for app-side reconciliation.',
  }),
  'browser.tabLeaseSnapshot': capabilityContract('browser.tabLeaseSnapshot', {
    actions: ['tabLeases.list', 'tabs.leases', 'getTabLeases'],
    actionClass: 'observe',
    outputSchemaVersion: 1,
    filters: ['sessionId', 'state', 'includeTabInfo'],
    summary: 'Return the persisted tab lease snapshot for diagnostics without releasing stale leases or mutating controlled tabs.',
  }),
  'browser.windowSnapshot': capabilityContract('browser.windowSnapshot', {
    actions: ['windows.list', 'browser.windows', 'getWindows'],
    actionClass: 'observe',
    filters: ['windowTypes', 'populate'],
    outputSchemaVersion: 1,
    summary: 'Return current Chrome window topology, normal-window ids, active tabs, and optional tab snapshots without changing focus.',
  }),
  'browser.visibility': capabilityContract('browser.visibility', {
    actions: ['browser.visibility.get', 'browser_visibility_get', 'getBrowserVisibility', 'browser.visibility.set', 'browser_visibility_set', 'setBrowserVisibility'],
    actionClass: 'read_only_reveal',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['windowId', 'visible', 'state'],
    summary: 'Read or change local Chrome window visibility/state without mutating page DOM or remote site state.',
  }),
  'browser.pageNavigation': capabilityContract('browser.pageNavigation', {
    actions: ['page.navigate', 'page.goto', 'page.waitForLoadState'],
    actionClass: 'navigate',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'url', 'wait_until', 'state', 'timeout_ms'],
    targetFields: ['url', 'wait_until', 'state'],
    summary: 'Navigate or wait for target-style page load states on an active controlled tab.',
  }),
  'browser.pageReadiness': capabilityContract('browser.pageReadiness', {
    actions: ['page.waitReady', 'waitForPage', 'waitTabReady'],
    actionClass: 'observe',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    bindings: ['sessionId', 'tabId'],
    summary: 'Wait for a controlled tab to finish loading and for the content-side DOM stability check to complete.',
  }),
  'browser.frameSnapshot': capabilityContract('browser.frameSnapshot', {
    actions: ['page.frames', 'frames.list', 'getPageFrames'],
    actionClass: 'observe',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    filters: ['tabId', 'includeContentScriptState', 'prepareContentScript'],
    summary: 'Return Chrome webNavigation frame topology and optional content-script availability per frame.',
  }),
  'browser.webMcp': capabilityContract('browser.webMcp', {
    actions: ['webmcp.listTools', 'webmcp_list_tools', 'tab.capabilities.webmcp.listTools', 'listWebMcpTools', 'webmcp.invokeTool', 'webmcp_invoke_tool', 'tab.capabilities.webmcp.invokeTool', 'invokeWebMcpTool'],
    actionClass: 'state_changing',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'toolName', 'tool_name', 'input', 'timeoutMs', 'timeout_ms', 'approvalToken'],
    targetFacades: ['tab.capabilities.webmcp.listTools', 'tab.capabilities.webmcp.invokeTool'],
    targetFields: ['tools', 'name', 'title', 'description', 'input_schema', 'annotations', 'readOnlyHint', 'untrustedContentHint', 'origin', 'pageUrl', 'result'],
    summary: 'List and invoke page-defined WebMCP tools registered through navigator.modelContext in an active controlled tab; target SDK facade maps input_schema to inputSchema and timeoutMs to timeout_ms.',
  }),
  'browser.pageScroll': capabilityContract('browser.pageScroll', {
    actions: ['page.scroll'],
    actionClass: 'navigate',
    inputSchemaVersion: 2,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'scroll_x', 'scroll_y', 'timeout_ms'],
    targetFields: ['scroll_x', 'scroll_y', 'node_id'],
    summary: 'Scroll the controlled page document with target-style scroll_x/scroll_y deltas while preserving legacy auto-scroll options.',
  }),
  'browser.pageClick': capabilityContract('browser.pageClick', {
    actions: ['page.click', 'page.doubleClick'],
    actionClass: 'read_only_reveal',
    inputSchemaVersion: 2,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'selector', 'modifiers', 'button', 'force', 'timeout_ms'],
    targetFields: ['modifiers', 'Alt', 'Control', 'ControlOrMeta', 'Meta', 'Shift', 'button', 'force'],
    summary: 'Dispatch target-style selector click or double-click events with normalized modifiers and mouse button metadata in a controlled tab.',
  }),
  'browser.pageHover': capabilityContract('browser.pageHover', {
    action: 'page.hover',
    actionClass: 'read_only_reveal',
    inputSchemaVersion: 2,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'selector'],
    summary: 'Dispatch page-local pointer and mouse hover events against an element in a controlled tab.',
  }),
  'browser.pageType': capabilityContract('browser.pageType', {
    action: 'page.type',
    actionClass: 'local_filter',
    inputSchemaVersion: 2,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'selector', 'value', 'replace', 'timeout_ms'],
    targetFields: ['value', 'replace', 'timeout_ms'],
    summary: 'Fill or append text in a target selector using target-style value/replace fields, dispatching page-local input and change events.',
  }),
  'browser.pagePointInspection': capabilityContract('browser.pagePointInspection', {
    actions: ['page.inspectPoint', 'page.hitTest', 'page.clickNode', 'node.click', 'page.scrollNode', 'node.scroll', 'page.waitForNode', 'node.wait'],
    actionClass: 'observe',
    inputSchemaVersion: 2,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'x', 'y', 'includeNonInteractable', 'node_id', 'scroll_x', 'scroll_y', 'timeout_ms'],
    targetFields: ['node_id', 'scroll_x', 'scroll_y', 'nodeId', 'boundingBox', 'selector.candidates', 'ariaName', 'visibleText'],
    summary: 'Return target-style element descriptors for elements under a viewport point and allow follow-up operations by content-side node_id in the same controlled tab.',
  }),
  'browser.pageSelectorWait': capabilityContract('browser.pageSelectorWait', {
    actions: ['page.waitForSelector', 'page.waitSelector'],
    actionClass: 'observe',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'selector', 'state', 'timeoutMs'],
    summary: 'Wait for a selector to become attached, detached, visible, or hidden in a controlled tab before page-local actions proceed.',
  }),
  'browser.pageCheckControl': capabilityContract('browser.pageCheckControl', {
    actions: ['page.check', 'page.setChecked'],
    actionClass: 'local_filter',
    inputSchemaVersion: 2,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'selector', 'checked', 'force', 'timeoutMs'],
    summary: 'Set checkbox or radio checked state in a controlled tab while dispatching page-local input and change events.',
  }),
  'browser.pageCheckState': capabilityContract('browser.pageCheckState', {
    action: 'page.isChecked',
    actionClass: 'observe',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'selector'],
    summary: 'Read checkbox or radio checked state in a controlled tab without mutating page state.',
  }),
  'browser.pageElementState': capabilityContract('browser.pageElementState', {
    action: 'page.isVisible',
    actionClass: 'observe',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'selector'],
    summary: 'Read whether an element is visible in a controlled tab without mutating page state.',
  }),
  'browser.pageElementValue': capabilityContract('browser.pageElementValue', {
    actions: ['page.getValue', 'page.getValues'],
    actionClass: 'observe',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'selector'],
    summary: 'Read form or element values in a controlled tab, including target-style string arrays for multi-value controls.',
  }),
  'browser.pageElementAttributes': capabilityContract('browser.pageElementAttributes', {
    actions: ['page.getAttribute', 'page.queryElements'],
    actionClass: 'observe',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'selector', 'name', 'relativeSelector'],
    summary: 'Read a single element attribute or target-style attribute/text snapshots for elements under a relative selector.',
  }),
  'browser.pageDomSnapshot': capabilityContract('browser.pageDomSnapshot', {
    action: 'page.domSnapshot',
    actionClass: 'observe',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId'],
    summary: 'Return a target-style cleaned DOM snapshot string for a controlled tab without mutating page state.',
  }),
  'browser.pageExport': capabilityContract('browser.pageExport', {
    actions: ['page.export', 'tab.export'],
    actionClass: 'read_only_export',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    bindings: ['sessionId', 'tabId', 'format'],
    targetFields: ['format', 'path'],
    targetBoundary: 'target_schema_confirmed_format_to_path; xwow_uses_download_runtime_for_local_path_resolution',
    summary: 'Export a controlled page with the target-style format enum and return the downloaded local path.',
  }),
  'browser.urlContent': capabilityContract('browser.urlContent', {
    actions: ['browser.fetchUrls', 'page.fetchUrls', 'urls.fetchContent'],
    actionClass: 'read_only_export',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    bindings: ['urls', 'content_type', 'timeout_ms'],
    targetFields: ['urls', 'content_type', 'results', 'url', 'title', 'content'],
    targetBoundary: 'target_schema_confirmed_urls_content_type_to_results; xwow_opens_temporary_tabs_and_closes_by_default',
    summary: 'Fetch content for one or more URLs using the target-style html/text/domSnapshot content_type enum.',
  }),
  'browser.pageScript': capabilityContract('browser.pageScript', {
    actions: ['page.evaluate', 'page.evaluateScript'],
    actionClass: 'state_changing',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'script', 'timeout_ms', 'approvalToken'],
    targetFields: ['value'],
    summary: 'Evaluate target-style page scripts in a controlled tab through CDP Runtime.evaluate; requires approval because script can mutate page or remote state.',
  }),
  'browser.pageClipboard': capabilityContract('browser.pageClipboard', {
    actions: ['page.readClipboard', 'clipboard.read', 'page.writeClipboard', 'clipboard.write', 'page.readClipboardText', 'clipboard.readText', 'page.writeClipboardText', 'clipboard.writeText'],
    actionClass: 'local_filter',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'items', 'entries'],
    targetFields: ['items', 'entries', 'mime_type', 'text', 'base64', 'presentation_style'],
    outputFields: ['items', 'text'],
    summary: 'Read or write page clipboard items or target-style plain text in a controlled tab.',
  }),
  'browser.pageFileChooser': capabilityContract('browser.pageFileChooser', {
    actions: ['page.waitForFileChooser', 'page.acceptFileChooser', 'fileChooser.accept', 'page.setInputFiles', 'fileChooser.snapshot'],
    actionClass: 'local_filter',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'fileChooserId', 'files', 'selector'],
    summary: 'Intercept and accept page file chooser dialogs or set file input paths in a controlled tab without submitting remote forms.',
  }),
  'browser.pageConsoleLogs': capabilityContract('browser.pageConsoleLogs', {
    actions: ['page.consoleLogs', 'tab_console_logs', 'tab.consoleLogs'],
    actionClass: 'observe',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    filters: ['filter', 'levels', 'limit'],
    bindings: ['sessionId', 'tabId', 'tab_id'],
    targetFacades: ['tab.consoleLogs'],
    targetFields: ['logs', 'level', 'message', 'timestamp', 'url'],
    summary: 'Return bounded target-style page console logs for a controlled tab using CDP Runtime and Log events.',
  }),
  'browser.pageSelect': capabilityContract('browser.pageSelect', {
    action: 'page.select',
    actionClass: 'local_filter',
    inputSchemaVersion: 2,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'tabId', 'selector', 'selections', 'value', 'label', 'index', 'timeout_ms'],
    targetFields: ['selections', 'value', 'label', 'index'],
    summary: 'Select one or more options in a page-local HTML select element using target-style value/label/index selections.',
  }),
  'browser.managedTabGroups': capabilityContract('browser.managedTabGroups', {
    actions: ['managedTabGroups.list', 'tabGroups.managed', 'getManagedTabGroups'],
    actionClass: 'observe',
    outputSchemaVersion: 1,
    summary: 'Return current managed Chrome tab group metadata for diagnostics and missed-event reconciliation.',
  }),
  'browser.activeTabObserver': capabilityContract('browser.activeTabObserver', {
    actions: ['activeTabObserver.snapshot', 'activeTabs.snapshot', 'getActiveTabObserverSnapshot'],
    actionClass: 'observe',
    outputSchemaVersion: 1,
    summary: 'Return active tab ids and per-window active tab ids for tab-state republish and missed-event reconciliation.',
  }),
  'browser.userContext': capabilityContract('browser.userContext', {
    actions: ['browser.context', 'userBrowser.context', 'getUserBrowserContext'],
    actionClass: 'observe',
    inputSchemaVersion: 2,
    outputSchemaVersion: 1,
    filters: ['include', 'includeAll', 'limit', 'tabsLimit', 'historyLimit', 'bookmarksLimit', 'topSitesLimit', 'readingListLimit', 'sessionsLimit'],
    summary: 'Return a single read-only browser context snapshot assembled from tabs, windows, history, bookmarks, top sites, reading list, and sessions readers.',
  }),
  'browser.cdp': capabilityContract('browser.cdp', {
    actions: ['cdp.send', 'cdp.attachments', 'cdp.attachedTargets', 'getCdpAttachments'],
    actionClass: 'observe',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    summary: 'Send safe Chrome Debugger Protocol commands and return structured results.',
  }),
  'browser.cdpPageRuntime': capabilityContract('browser.cdpPageRuntime', {
    actions: ['cdp.screenshot', 'page.screenshot', 'cdp.viewportSet', 'cdp.viewportReset', 'viewport.set', 'viewport.reset', 'browser_viewport_set', 'browser_viewport_reset', 'viewport.state', 'cdp.viewportState', 'getViewportState'],
    actionClass: 'navigate',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    targetFields: ['fullPage', 'cropX', 'cropY', 'cropWidth', 'cropHeight', 'data'],
    summary: 'Run common screenshot and viewport primitives through typed wrappers, with a read-only viewport restore-state snapshot.',
  }),
  'browser.pixelInput': capabilityContract('browser.pixelInput', {
    actions: ['input.mouseMove', 'input.mouseClick', 'input.mouseDrag', 'mouse.drag', 'input.mouseWheel', 'mouse.wheel', 'input.keyboardType', 'input.keyboardPress', 'input.keyboardCombo', 'keyboard.combo'],
    actionClass: 'local_filter',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    targetFields: ['keys', 'ControlOrMeta', 'Alt', 'Control', 'Meta', 'Shift'],
    summary: 'Dispatch CDP mouse/keyboard input with coordinate normalization, visible cursor state, drag paths, and common keyboard combos.',
  }),
  'browser.actionPolicy': capabilityContract('browser.actionPolicy', {
    action: 'browser.action',
    actionClass: 'observe',
    outputSchemaVersion: 2,
    summary: 'Expose browser action classes and dangerous-action policy metadata.',
  }),
  'browser.approvalTokenPolicy': capabilityContract('browser.approvalTokenPolicy', {
    actionClass: 'state_changing',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    bindings: ['actionType', 'actionTypes', 'method', 'methods', 'sessionId', 'tabId', 'requestId', 'requestIds', 'tokenId'],
    summary: 'Describe approval token requirements and optional binding checks for state-changing browser actions.',
  }),
  'browser.protocolSchemas': capabilityContract('browser.protocolSchemas', {
    actionClass: 'observe',
    inputSchemaVersion: BROWSER_PROTOCOL_SCHEMA_VERSION,
    outputSchemaVersion: NATIVE_METHOD_SCHEMA_CATALOG_VERSION,
    outputFields: ['schemaVersion', 'protocolSchemaVersion', 'methods'],
    summary: 'Expose versioned target-style native browser-control method schemas and normalize params such as session_id, turn_id, keep, target, and timeout_ms.',
  }),
  'browser.unsupportedCommandFallback': capabilityContract('browser.unsupportedCommandFallback', {
    actions: ['executeUnhandledCommand', 'command.unsupported'],
    actionClass: 'observe',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    bindings: ['sessionId', 'turnId', 'unsupportedMethod'],
    errorCode: TARGET_UNSUPPORTED_COMMAND_ERROR_CODE,
    targetMessage: TARGET_UNSUPPORTED_COMMAND_MESSAGE_TEMPLATE,
    targetSessionActivation: true,
    routeFailedEvent: 'route.failed',
    xwowUnknownNativeMethodErrorCode: XWOW_UNKNOWN_NATIVE_METHOD_ERROR_CODE,
    summary: 'Activate the browser-control session for target-style unsupported command handling, then return a structured Chrome does-not-support-command error.',
  }),
  'browser.eventReplay': capabilityContract('browser.eventReplay', {
    action: 'browser.events',
    actionClass: 'observe',
    filters: ['eventType', 'sessionId', 'turnId', 'bridgeMethod', 'since', 'afterEventId', 'limit'],
    replaySources: ['browserEventBridgeLog', 'browserSessionEvents', 'downloadEvents', 'cdpEvents'],
    nativeEventMethods: ['onCDPEvent', 'onDownloadChange', 'onBrowserLifecycleEvent', 'onBrowserSessionEvent'],
    outputFields: ['events', 'hasMore', 'newestEventId', 'newestEmittedAt'],
    summary: 'Replay aggregated browser events from bridge, session, download, and CDP stores for app/runtime reconciliation.',
  }),
  'browser.cdpEvents': capabilityContract('browser.cdpEvents', {
    actions: ['cdp.events', 'getCdpEvents', 'cdp.events.summary', 'getCdpEventSummary'],
    actionClass: 'observe',
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    filters: ['method', 'tabId', 'targetId', 'since', 'afterEventId', 'limit'],
    outputFields: ['events', 'byMethod', 'bySource', 'checkpoint'],
    summary: 'Replay raw Chrome debugger events captured from chrome.debugger.onEvent and return CDP-only checkpoints for target-style event reconciliation.',
  }),
  'page.assetInventory': capabilityContract('page.assetInventory', {
    actions: ['page.assets', 'assets.page', 'pageAssets', 'tab_page_assets_list', 'tab.capabilities.pageAssets.list'],
    actionClass: 'observe',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    targetFacades: ['tab.capabilities.pageAssets.list'],
    summary: 'Read page resource inventory without mutating the page or triggering downloads.',
  }),
  'page.assetBundle': capabilityContract('page.assetBundle', {
    actions: ['page.assets.bundle', 'assets.bundle', 'pageAssetBundle', 'tab_page_assets_bundle', 'tab.capabilities.pageAssets.bundle'],
    actionClass: 'read_only_export',
    inputSchemaVersion: 2,
    outputSchemaVersion: 3,
    outputFields: ['assets', 'failures', 'summary', 'targetBundle', 'bundle', 'assetLibraryRegistration'],
    targetFields: ['assets', 'directoryPath', 'failures', 'manifestPath', 'summary'],
    targetFacades: ['tab.capabilities.pageAssets.bundle'],
    bindings: ['artifactBinding', 'jobId', 'storeId', 'pageRole', 'sessionId', 'turnId'],
    summary: 'Fetch bounded page assets and return a target bundle plus XWOW artifact and asset-library registration manifests.',
  }),
  'browser.finalizedTabBadges': capabilityContract('browser.finalizedTabBadges', {
    actions: ['tabs.finalize', 'tabs.finalizedBadges'],
    actionClass: 'observe',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    summary: 'Track handoff/deliverable tabs and seen/unseen favicon badge state.',
  }),
  'browser.nativeMessaging': capabilityContract('browser.nativeMessaging', {
    actions: ['native.status', 'native.connect', 'native.disconnect', 'native.request'],
    actionClass: 'observe',
    inputSchemaVersion: 2,
    outputSchemaVersion: 2,
    summary: 'Bridge the extension and native host with JSON-RPC envelopes and reconnect telemetry.',
  }),
  'browser.lifecycleGuard': capabilityContract('browser.lifecycleGuard', {
    actions: ['lifecycle.status', 'browser.lifecycleStatus', 'getLifecycleStatus'],
    actionClass: 'observe',
    outputSchemaVersion: 1,
    summary: 'Return pending update, heartbeat, extension instance, and active-control lifecycle status.',
  }),
  'browser.sidePanelStatus': capabilityContract('browser.sidePanelStatus', {
    actions: ['sidePanel.status', 'sidepanel.status', 'getSidePanelStatus'],
    actionClass: 'observe',
    outputSchemaVersion: 1,
    filters: ['windowId'],
    summary: 'Return current side panel open state by Chrome window for bootstrap gating and diagnostics.',
  }),
  'browser.sidePanelControl': capabilityContract('browser.sidePanelControl', {
    actions: ['sidePanel.open', 'sidepanel.open', 'openSidePanel', 'sidePanel.close', 'sidepanel.close', 'closeSidePanel', 'sidePanel.toggle', 'sidepanel.toggle', 'toggleSidePanel'],
    actionClass: 'read_only_reveal',
    inputSchemaVersion: 2,
    outputSchemaVersion: 1,
    bindings: ['windowId'],
    summary: 'Open, close, or toggle the extension side panel control surface for a Chrome window.',
  }),
};

export function buildBrowserCapabilityMetadata(options = {}) {
  const manifest = options.manifest || chrome.runtime.getManifest();
  const permissions = manifest.permissions || [];
  const nativeStatus = options.nativeStatus || { state: 'unknown' };
  const activeSession = options.activeSession || null;
  const nativeMethodSchemas = getNativeMethodSchemaCatalog();
  return {
    capabilitySchemaVersion: 1,
    pluginId: options.pluginId || 'xwow-browser-data-ai',
    extensionId: chrome.runtime.id,
    name: manifest.name,
    version: manifest.version,
    manifestVersion: manifest.manifest_version,
    type: 'extension',
    capabilities: [...PLUGIN_CAPABILITIES],
    targetBrowserInfoShape: {
      name: 'Chrome',
      type: 'extension',
      capabilities: {
        tab: [
          { id: 'pageAssets', description: 'List assets already observed in the current page state and bundle selected assets into a temporary local artifact.' },
          { id: 'webmcp', description: 'List and invoke page-defined WebMCP tools registered through navigator.modelContext in the active tab.' },
        ],
      },
      metadataFields: ['extensionId', 'extensionInstanceId'],
      webMcpBuildGate: 'target enables webmcp when buildChannel !== prod',
    },
    targetCapabilityRegistry: {
      tab: {
        pageAssets: {
          listAction: 'tab_page_assets_list',
          bundleAction: 'tab_page_assets_bundle',
          sdkMethods: ['tab.capabilities.pageAssets.list', 'tab.capabilities.pageAssets.bundle'],
        },
        webmcp: {
          listAction: 'webmcp_list_tools',
          invokeAction: 'webmcp_invoke_tool',
          sdkMethods: ['tab.capabilities.webmcp.listTools', 'tab.capabilities.webmcp.invokeTool'],
        },
        consoleLogs: {
          listAction: 'tab_console_logs',
          sdkMethods: ['tab.consoleLogs'],
          targetSchema: {
            input: ['browser_id', 'tab_id', 'filter', 'levels', 'limit'],
            output: ['logs[].level', 'logs[].message', 'logs[].timestamp', 'logs[].url'],
          },
        },
      },
    },
    capabilityContracts: buildCapabilityContracts(),
    browserControl: {
      cdpProtocolVersion: options.cdpProtocolVersion || '',
      debugger: Boolean(chrome.debugger),
      pixelInput: true,
      pixelInputEvents: true,
      mouseDrag: true,
      mouseDragActions: ['input.mouseDrag', 'mouse.drag'],
      mouseWheel: true,
      mouseWheelActions: ['input.mouseWheel', 'mouse.wheel'],
      pixelInputKeyModifiers: ['Alt', 'Control', 'ControlOrMeta', 'Meta', 'Shift'],
      keyboardCombo: true,
      keyboardComboActions: ['input.keyboardCombo', 'keyboard.combo'],
      keyboardComboKeys: ['Ctrl+A', 'Meta+A', 'Enter', 'Tab', 'Escape', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'],
      cursorOverlay: true,
      cursorOverlayRootId: 'codex-agent-overlay-root',
      cursorOverlayClassName: 'codex-agent-overlay',
      cursorAssetDomMarker: 'data-browser-agent-cursor-asset',
      cursorArrivalMessageType: 'AGENT_CURSOR_ARRIVED',
      cursorStateMessageType: 'AGENT_CURSOR_STATE',
      cursorStateRequestMessageType: 'GET_AGENT_CURSOR_STATE',
      cursorAssetPath: 'images/cursor-chat.png',
      controlBadge: true,
      controlBadgeMessageType: 'AGENT_CONTROL_BADGE',
      controlBadgeStateRequestMessageType: 'GET_AGENT_CONTROL_BADGE_STATE',
      controlBadgeRootId: 'codex-agent-overlay-root',
      controlBadgeElementId: 'xwow-browser-data-ai-control-badge',
      faviconBadgeMarker: 'codex-favicon-badge',
      faviconBadgeMessageType: 'TAB_FAVICON_BADGE',
      faviconBadgeTargetStates: ['active', 'deliverable', 'handoff'],
      faviconBadgeXwowStates: ['unseen-deliverable', 'unseen-handoff'],
      pageAssetInventory: true,
      pageAssetInventoryActions: ['page.assets', 'assets.page', 'pageAssets', 'tab_page_assets_list', 'tab.capabilities.pageAssets.list'],
      pageAssetBundle: true,
      pageAssetBundleActions: ['page.assets.bundle', 'assets.bundle', 'pageAssetBundle', 'tab_page_assets_bundle', 'tab.capabilities.pageAssets.bundle'],
      targetPageAssetsCapabilityId: 'pageAssets',
      targetPageAssetsDescription: 'List assets already observed in the current page state and bundle selected assets into a temporary local artifact.',
      targetPageAssetsListCommand: 'tab_page_assets_list',
      targetPageAssetsBundleCommand: 'tab_page_assets_bundle',
      targetPageAssetsFacades: ['tab.capabilities.pageAssets.list', 'tab.capabilities.pageAssets.bundle'],
      targetPageAssetsListInputFields: ['browser_id', 'tab_id'],
      targetPageAssetsListOutputFields: ['id', 'assets', 'inlineSvgs', 'pageUrl', 'summary'],
      targetPageAssetsAssetFields: ['id', 'kind', 'name', 'sources', 'url'],
      targetPageAssetsSourceFields: ['kind', 'nodeId?', 'property?'],
      targetPageAssetsInlineSvgFields: ['id', 'markup', 'name'],
      targetPageAssetsSummaryFields: ['byKind', 'inlineSvgCount', 'totalCount'],
      targetPageAssetsKinds: ['font', 'image', 'script', 'stylesheet', 'video', 'other'],
      targetPageAssetsBundleInputFields: ['browser_id', 'tab_id', 'inventoryId', 'assetIds?', 'kinds?'],
      targetPageAssetsBundleOutputFields: ['assets', 'directoryPath', 'failures', 'manifestPath', 'summary'],
      targetPageAssetsBundleAssetFields: ['contentType', 'id', 'kind', 'name', 'path', 'url'],
      targetPageAssetsBundleFailureFields: ['contentType', 'id', 'name', 'reason', 'url'],
      targetPageAssetsBundleSummaryFields: ['downloadedCount', 'elapsedMs', 'failedCount', 'requestedCount'],
      xwowPageAssetEnhancements: ['groupedInventoryCompatibility', 'hashManifest', 'dataUrlOption', 'artifactBinding', 'suggestedLibrary', 'assetLibraryRegistration'],
      pageAssetBundleOutputSchemaVersion: 3,
      pageAssetLibraryRegistration: true,
      pageAssetLibraryRegistrationSchemaVersion: 1,
      pageAssetLibraryRegistrationFields: ['schemaVersion', 'source', 'binding', 'inventoryId', 'pageUrl', 'directoryPath', 'manifestPath', 'entryCount', 'libraries', 'entries'],
      pageAssetLibraryRegistrationEntryFields: ['artifactId', 'filename', 'library', 'sourceUrl', 'pageUrl', 'inventoryId', 'bundleDirectoryPath', 'bundleManifestPath', 'mimeType', 'byteSize', 'sha256', 'title', 'kind', 'group', 'role', 'jobId', 'storeId', 'sessionId', 'turnId', 'source'],
      pageAssetLibraryRegistrationSource: 'browser_page_asset_bundle',
      pageAssetLibraryRegistrationMutation: 'none_plugin_returns_manifest_only',
      targetTabCapabilities: ['pageAssets', 'webmcp', 'consoleLogs'],
      targetTabCapabilityActions: {
        pageAssets: ['tab_page_assets_list', 'tab_page_assets_bundle', 'tab.capabilities.pageAssets.list', 'tab.capabilities.pageAssets.bundle'],
        webmcp: ['webmcp_list_tools', 'webmcp_invoke_tool'],
        consoleLogs: ['tab_console_logs', 'tab.consoleLogs'],
      },
      pageAssetTargetAliases: ['tab_page_assets_list', 'tab_page_assets_bundle'],
      dynamicContentInjection: true,
      dynamicContentPrepare: true,
      dynamicContentDefaultAllFrames: false,
      targetContentScriptFile: 'content-scripts/codex.js',
      targetContentPingType: 'CONTENT_PING',
      targetContentPingTimeoutMs: 1000,
      targetContentScriptMessages: ['CONTENT_PING', 'AGENT_CURSOR_STATE', 'GET_AGENT_CURSOR_STATE', 'AGENT_CURSOR_ARRIVED', 'AGENT_CONTROL_BADGE', 'GET_AGENT_CONTROL_BADGE_STATE', 'TAB_FAVICON_BADGE'],
      xwowContentScriptFiles: ['content-scripts/codex.js'],
      xwowBundledContentModules: ['siteAdapters', 'domReader', 'pageActions', 'pageAssetInventory', 'cursorOverlay', 'controlBadge', 'faviconBadge'],
      xwowContentPingType: 'xwow-data-ai:content-ping',
      xwowContentModuleExtensions: ['domReader', 'pageActions', 'pageAssetInventory', 'cursorOverlay', 'controlBadge', 'faviconBadge'],
      dynamicContentInjectionEvents: true,
      cdpPageRuntime: true,
      viewportActions: ['viewport.set', 'viewport.reset', 'browser_viewport_set', 'browser_viewport_reset'],
      viewportTargetAliases: ['browser_viewport_set', 'browser_viewport_reset'],
      viewportStateSnapshot: true,
      viewportStateActions: ['viewport.state', 'cdp.viewportState', 'getViewportState'],
      cdpLifecycleEvents: true,
      cdpCommandEvents: true,
      targetCdpDefaultTimeoutMs: 10000,
      xwowCdpDefaultTimeoutMs: 10000,
      targetCdpTimeoutErrorName: 'CdpCommandTimeoutError',
      targetCdpTimeoutMessageTemplate: 'Timed out after <timeoutMs>ms waiting for CDP command <method>.',
      targetCdpSpecialMethods: ['Target.getTargets -> chrome.debugger.getTargets()'],
      targetCdpUnattachedError: 'Debugger unattached',
      targetCdpTimeoutRecovery: ['tab target timeout', 'best-effort detach tab', 'clear attached tab set'],
      xwowCdpTimeoutRecovery: ['isCdpCommandTimeoutError', 'detachAttachedDebuggersForTabs([tabId])', 'cdpCommand.command.timeout event', 'cdpLifecycle.detach.best_effort event'],
      targetDebuggerDetachListenerEffect: ['delete attached tabId', 'delete attached targetId', 'delete targetId owner tab mapping'],
      targetDebuggerDetachEventSource: 'chrome.debugger.onDetach',
      targetExternalDetachEventKind: 'debugger.detached',
      targetCommandDetachEventKind: 'debugger.detached.command',
      targetBestEffortDetachEventKind: 'debugger.detached.best_effort',
      cdpEventReplay: true,
      cdpEventReplayActions: ['cdp.events', 'getCdpEvents'],
      cdpEventSummary: true,
      cdpEventSummaryActions: ['cdp.events.summary', 'getCdpEventSummary'],
      cdpEventReplayFilters: ['method', 'tabId', 'targetId', 'since', 'afterEventId', 'limit'],
      cdpAttachmentSnapshot: true,
      cdpAttachmentSnapshotActions: ['cdp.attachments', 'cdp.attachedTargets', 'getCdpAttachments'],
      cdpAttachmentSnapshotFields: ['attachedTabIds', 'attachedTargetIds', 'attachedTabs', 'attachedTargets', 'attachedCount', 'hasAttachedCdp', 'snapshotAt'],
      cdpTargetOwnerMap: true,
      cdpTargetOwnerMapSource: 'attachedCdpTargetTabs',
      targetAttachRequiresOwnerTabId: true,
      targetDetachRequiresOwnerTabId: true,
      bestEffortDetachResultFields: ['success', 'rawTargetCount', 'targetTabIds', 'detachedTabIds', 'detachedTargetIds', 'detachedTabs', 'detachedTargets'],
      targetBestEffortDetachSource: 'chrome.debugger.getTargets + attached_set',
      xwowAttachmentSnapshotSource: 'cdpTransport_attached_sets',
      sessionLease: true,
      tabLeaseSnapshot: true,
      tabLeaseSnapshotActions: ['tabLeases.list', 'tabs.leases', 'getTabLeases'],
      targetTabLeaseStorageKey: 'TAB_LEASES',
      xwowTabLeaseStorageKey: 'xwowBrowserDataAiTabLeases',
      targetTabGroupStorageKey: 'TAB_GROUPS',
      xwowTabGroupStorageKey: 'xwowBrowserDataAiTabGroups',
      targetFaviconBadgeStorageKey: 'TAB_FAVICON_BADGES',
      xwowFaviconBadgeStorageKey: 'xwowBrowserDataAiFinalizedTabBadges',
      targetTabLeaseDurableStates: ['active', 'handoff'],
      xwowTabLeaseAcceptedStates: ['active', 'handoff', 'deliverable', 'released'],
      deliverableLeaseRetention: 'released_after_finalize',
      targetSessionTabHandlers: ['getTabs', 'claimUserTab', 'createTab', 'finalizeTabs', 'nameSession', 'turnEnded'],
      targetCreateTabSourceApi: 'chrome.tabs.create({ active: false, url: "about:blank", windowId })',
      targetCreateTabFallbackWindowApi: 'chrome.windows.create({ focused: false, type: "normal", url: "about:blank" })',
      targetCreateTabOutputFields: ['id', 'title?', 'active?', 'url?'],
      targetClaimUserTabInputFields: ['session_id', 'turn_id', 'tabId'],
      targetClaimUserTabFlow: ['resolveSession', 'requireTurnId', 'claimUserTab(turnId, tabId)', 'trackTab'],
      targetGetTabsOutputFields: ['tabs[].id', 'tabs[].title?', 'tabs[].url?'],
      targetFinalizeInputFields: ['session_id', 'turn_id', 'keep'],
      targetFinalizeKeepFields: ['tabId', 'status'],
      targetFinalizeKeepArrayCanBeEmpty: true,
      targetRemoveTabsApi: 'chrome.tabs.remove(tabId | tabId[])',
      targetRemoveTabsHelperFlow: ['ignore_empty', 'remove_single_tab_as_scalar', 'remove_multiple_tabs_as_array'],
      targetTurnEndedInputFields: ['session_id', 'turn_id'],
      targetTurnEndedFlow: ['requireSessionId', 'requireTurnId', 'resolveLiveSession', 'session.endTurn(turnId)', 'fallbackTabLeases.releaseActiveTurn(sessionId, turnId)'],
      targetSessionEndTurnOrder: ['listSessionTabs', 'detachAttachedDebuggersBestEffort', 'stopSessions([sessionId])', 'releaseActiveTurn(sessionId, turnId)', 'clearActiveTabAndCurrentTurn'],
      targetTurnEndedFallback: 'tabLeases.releaseActiveTurn(sessionId, turnId)',
      xwowTurnEndedOrder: ['markTurnEnded', 'releaseActiveTurnLeases', 'releaseTabsFromManagedGroups', 'clearCursorOverlayForLeases', 'untrackRuntimeTabs', 'clearLeaseFaviconBadges', 'updateActiveBrowserSession'],
      targetHandoffResumeFlow: ['getSessionHandoffLeases', 'chrome.tabs.get(tabId)', 'releaseStaleHandoffTabs', 'resumeHandoffTabs(sessionId, turnId, liveTabIds)', 'reconcileManagedGroupForTabs', 'selectActiveHandoffOrFirstResumedTab'],
      targetHandoffStaleReleaseReason: 'stale_handoff_tab',
      targetTabLeaseLifecycleListeners: ['chrome.tabs.onRemoved -> removeTab', 'chrome.tabs.onReplaced -> replaceTab'],
      targetReplacedTabLeaseFlow: ['deleteRemovedTabLease', 'setAddedTabLeaseWithSameFieldsAndNewTabId'],
      xwowHandoffResumeEnhancements: ['sessionEventReplay', 'staleTabIdsResult', 'releasedLeasesResult', 'ownedTabIdsCleanup', 'faviconBadgeReconcile'],
      finalizeKeepStatuses: ['handoff', 'deliverable'],
      targetClaimRejectsChromeInternalTabs: true,
      targetClaimConflictMessage: 'Tab <tabId> is already part of browser session <sessionId>',
      targetFinalizeReleaseOrder: ['markFinalizedBadges', 'detachAttachedDebuggers', 'releaseDeliverableFromManagedGroups', 'closeUnkeptAgentTabs', 'refreshManagedGroups', 'untrackRuntimeTabs', 'releaseDeliverableAndUnkeptLeases', 'retainHandoffLeases'],
      xwowFinalizeReleaseOrder: ['markFinalizedBadges', 'detachAttachedDebuggers', 'untrackRuntimeTabs', 'releaseManagedGroups', 'releaseDeliverableAndUnkeptLeases', 'clearReleasedUserFaviconBadges', 'closeUnkeptAgentTabs', 'refreshManagedGroups', 'retainHandoffLeases'],
      finalizeValidationMessages: ['finalizeTabs requires a keep array', 'finalizeTabs received invalid tab entry', 'finalizeTabs requires an integer tabId', 'finalizeTabs cannot keep unknown tab <tabId>', 'finalizeTabs received invalid status <status>', 'finalizeTabs received duplicate tab <tabId>'],
      tabLifecycleEvents: true,
      tabLifecycleEventActions: ['tab.lifecycleEvents', 'tabs.lifecycleEvents', 'tabLifecycle.events', 'getTabLifecycleEvents'],
      tabLifecycleSnapshot: true,
      tabLifecycleSnapshotActions: ['tab.lifecycleSnapshot', 'tabs.lifecycleSnapshot', 'tabLifecycle.snapshot', 'getTabLifecycleSnapshot'],
      sessionTabs: true,
      sessionActiveRequests: true,
      sessionInMemoryRuntime: true,
      sessionTurnHandoff: true,
      controlledTabClose: true,
      controlledTabCloseActions: ['tab.close', 'tab.remove', 'closeTab'],
      controlledTabActivation: true,
      controlledTabActivationActions: ['tab.activate', 'activateTab', 'focusTab'],
      controlledTabNavigation: true,
      controlledTabNavigationActions: ['tab.navigate', 'navigateTab', 'tab.reload', 'reloadTab'],
      controlledWindowCreation: true,
      controlledWindowCreationActions: ['window.create', 'browser.windowCreate', 'createWindow', 'tab.create:newWindow'],
      windowSnapshot: true,
      windowSnapshotActions: ['windows.list', 'browser.windows', 'getWindows'],
      browserVisibility: true,
      browserVisibilityActions: ['browser.visibility.get', 'browser_visibility_get', 'getBrowserVisibility', 'browser.visibility.set', 'browser_visibility_set', 'setBrowserVisibility'],
      pageNavigation: true,
      pageNavigationActions: ['page.navigate', 'page.goto'],
      pageLoadStateActions: ['page.waitForLoadState'],
      pageLoadStates: ['load', 'domcontentloaded', 'networkidle'],
      pageNavigationWaitUntilStates: ['load', 'domcontentloaded', 'networkidle', 'commit'],
      pageNavigationTargetFields: ['url', 'wait_until', 'state', 'timeout_ms'],
      pageReadiness: true,
      pageReadinessActions: ['page.waitReady', 'waitForPage', 'waitTabReady'],
      frameSnapshot: true,
      frameSnapshotActions: ['page.frames', 'frames.list', 'getPageFrames'],
      frameContentScriptState: true,
      webMcp: true,
      webMcpActions: ['webmcp.listTools', 'webmcp_list_tools', 'tab.capabilities.webmcp.listTools', 'listWebMcpTools', 'webmcp.invokeTool', 'webmcp_invoke_tool', 'tab.capabilities.webmcp.invokeTool', 'invokeWebMcpTool'],
      webMcpListActions: ['webmcp.listTools', 'webmcp_list_tools', 'tab.capabilities.webmcp.listTools', 'listWebMcpTools'],
      webMcpInvokeActions: ['webmcp.invokeTool', 'webmcp_invoke_tool', 'tab.capabilities.webmcp.invokeTool', 'invokeWebMcpTool'],
      webMcpTargetFacades: ['tab.capabilities.webmcp.listTools', 'tab.capabilities.webmcp.invokeTool'],
      webMcpTargetFields: ['tools', 'input_schema', 'annotations', 'result'],
      webMcpFacadeMappings: {
        listTools: { action: 'webmcp_list_tools', output: 'tools[].input_schema -> tool.inputSchema' },
        invokeTool: { action: 'webmcp_invoke_tool', input: 'toolName -> tool_name, timeoutMs -> timeout_ms', output: 'result' },
      },
      webMcpRequiresActiveLease: true,
      webMcpInvokeRequiresApproval: true,
      pageScroll: true,
      pageScrollActions: ['page.scroll'],
      pageScrollTargetFields: ['scroll_x', 'scroll_y', 'node_id'],
      pageScrollBoundary: 'page.scroll=document delta; page.scrollNode=node_id delta; input.mouseWheel=CDP physical wheel',
      pageClick: true,
      pageClickActions: ['page.click', 'page.doubleClick'],
      pageClickTargetFields: ['modifiers', 'button', 'force', 'timeout_ms'],
      pageClickModifiers: ['Alt', 'Control', 'ControlOrMeta', 'Meta', 'Shift'],
      pageHover: true,
      pageHoverActions: ['page.hover'],
      pageType: true,
      pageTypeActions: ['page.type'],
      pageTypeTargetFields: ['value', 'replace', 'timeout_ms'],
      pagePointInspection: true,
      pagePointInspectionActions: ['page.inspectPoint', 'page.hitTest'],
      pageNodeActions: ['page.clickNode', 'node.click', 'page.scrollNode', 'node.scroll', 'page.waitForNode', 'node.wait'],
      pagePointInspectionTargetFields: ['include_non_interactable', 'node_id', 'nodeId', 'boundingBox', 'selector.candidates', 'ariaName', 'visibleText'],
      pageSelectorWait: true,
      pageSelectorWaitActions: ['page.waitForSelector', 'page.waitSelector'],
      pageSelectorWaitStates: ['attached', 'detached', 'visible', 'hidden'],
      pageCheckControl: true,
      pageCheckControlActions: ['page.check', 'page.setChecked'],
      pageCheckState: true,
      pageCheckStateActions: ['page.isChecked'],
      pageCheckTargetFields: ['checked', 'force', 'timeout_ms', 'value'],
      pageElementState: true,
      pageElementStateActions: ['page.isVisible'],
      pageElementValue: true,
      pageElementValueActions: ['page.getValue', 'page.getValues'],
      pageElementValueTargetFields: ['value', 'values'],
      pageElementAttributes: true,
      pageElementAttributeActions: ['page.getAttribute', 'page.queryElements'],
      pageElementAttributeTargetFields: ['name', 'relative_selector', 'attributes', 'inner_text', 'text_content'],
      pageDomSnapshot: true,
      pageDomSnapshotActions: ['page.domSnapshot'],
      pageDomSnapshotTargetFields: ['dom_snapshot'],
      pageExport: true,
      pageExportActions: ['page.export', 'tab.export'],
      pageExportFormats: ['pdf', 'md', 'xlsx', 'csv', 'docx', 'pptx'],
      pageExportTargetFields: ['format', 'path'],
      pageExportBoundary: 'pdf_uses_CDP_printToPDF; text_formats_use_lightweight_page_snapshot_until_native_office_generators_are_added',
      urlContentFetch: true,
      urlContentActions: ['browser.fetchUrls', 'page.fetchUrls', 'urls.fetchContent'],
      urlContentTypes: ['html', 'text', 'domSnapshot'],
      urlContentTargetFields: ['urls', 'content_type', 'results', 'url', 'title', 'content'],
      urlContentBoundary: 'temporary_tabs_closed_by_default; no_capture_ingest; http_https_only',
      pageScript: true,
      pageScriptActions: ['page.evaluate', 'page.evaluateScript'],
      pageScriptRequiresApproval: true,
      pageScriptTargetFields: ['script', 'timeout_ms', 'value'],
      pageClipboard: true,
      pageClipboardActions: ['page.readClipboard', 'clipboard.read', 'page.writeClipboard', 'clipboard.write', 'page.readClipboardText', 'clipboard.readText', 'page.writeClipboardText', 'clipboard.writeText'],
      pageClipboardTargetFields: ['items', 'entries', 'mime_type', 'text', 'base64', 'presentation_style'],
      pageClipboardTextActions: ['page.readClipboardText', 'clipboard.readText', 'page.writeClipboardText', 'clipboard.writeText'],
      pageClipboardTextTargetFields: ['text'],
      pageFileChooser: true,
      pageFileChooserActions: ['page.waitForFileChooser', 'page.acceptFileChooser', 'fileChooser.accept', 'page.setInputFiles'],
      pageFileChooserSnapshotActions: ['fileChooser.snapshot'],
      pageFileChooserTargetFields: ['file_chooser_id', 'is_multiple', 'files', 'timeout_ms'],
      pageConsoleLogs: true,
      pageConsoleLogActions: ['page.consoleLogs', 'tab_console_logs', 'tab.consoleLogs'],
      pageConsoleLogLevels: ['debug', 'info', 'log', 'warn', 'error'],
      pageConsoleLogTargetFields: ['logs', 'level', 'message', 'timestamp', 'url'],
      pageConsoleLogSnapshot: options.consoleLogSnapshot || null,
      pageSelect: true,
      pageSelectActions: ['page.select'],
      pageSelectTargetFields: ['selections', 'value', 'label', 'index', 'timeout_ms'],
      pageScreenshot: true,
      pageScreenshotActions: ['page.screenshot', 'cdp.screenshot'],
      pageScreenshotTargetFields: ['fullPage', 'cropX', 'cropY', 'cropWidth', 'cropHeight', 'data'],
      sessionEventBridge: true,
      managedTabGroups: true,
      managedTabGroupSnapshot: true,
      managedTabGroupSnapshotActions: ['managedTabGroups.list', 'tabGroups.managed', 'getManagedTabGroups'],
      managedTabGroupEvents: true,
      activeTabObserver: true,
      activeTabObserverSnapshot: true,
      activeTabObserverSnapshotActions: ['activeTabObserver.snapshot', 'activeTabs.snapshot', 'getActiveTabObserverSnapshot'],
      activeTabObserverEvents: true,
      targetActiveTabObserverStateFields: ['activeTabIds', 'activeTabIdByWindowId'],
      targetActiveTabObserverTrackedEvents: ['tabs.onActivated', 'tabs.onCreated', 'tabs.onRemoved', 'tabs.onReplaced', 'tabs.onAttached', 'tabs.onDetached', 'windows.onCreated', 'windows.onFocusChanged', 'windows.onRemoved'],
      xwowActiveTabObserverTrackedEvents: ['tabs.onActivated', 'tabs.onCreated', 'tabs.onUpdated', 'tabs.onRemoved', 'tabs.onReplaced', 'tabs.onAttached', 'tabs.onDetached', 'windows.onCreated', 'windows.onFocusChanged', 'windows.onRemoved'],
      targetActiveTabObserverChangedPayload: 'tabIds_only',
      xwowActiveTabObserverChangedPayload: 'tabIds_snapshot_reason_metadata',
      targetDuplicateActivationRepublish: false,
      targetTabStateRepublishTrigger: 'active_tab_observer_changed_tab_ids',
      targetTabStateRepublishMethod: 'republishTabStates',
      targetObservedTabPredicate: 'activeTabIds.has(tabId)',
      targetCursorVisibilityRule: 'inactive_controlled_tab_cursor_visible_false',
      xwowCursorVisibilityRule: 'inactive_controlled_tab_cursor_visible_false_with_snapshot_metadata',
      userBrowserContext: true,
      userBrowserContextActions: ['browser.context', 'userBrowser.context', 'getUserBrowserContext'],
      userBrowserContextIncludes: ['activeTab', 'tabs', 'windows', 'history', 'bookmarks', 'topSites', 'readingList', 'recentlyClosed', 'sessionDevices'],
      targetUserStateConfirmedHandlers: ['getUserTabs', 'getUserHistory'],
      targetUserStatePermissionInferredExtensions: ['getUserBookmarks', 'getUserTopSites', 'getUserReadingList', 'getUserSessions'],
      targetUserStatePermissionOnlyApis: ['bookmarks', 'topSites', 'readingList', 'sessions'],
      targetUserStateUnconfirmedHandlers: ['getUserBookmarks', 'getUserTopSites', 'getUserReadingList', 'getUserSessions', 'sessions.devices'],
      targetUserStateEvidence: 'getUserTabs_getUserHistory_confirmed_manifest_permissions_only_for_extended_readers',
      xwowUserStateExtensionsAreObserveOnly: true,
      targetGetUserTabsSourceApi: 'chrome.tabs.query({})',
      targetGetUserTabsLimit: 1000,
      targetGetUserTabsSort: ['lastAccessed desc', 'windowId asc', 'index asc'],
      targetGetUserTabsOutputShape: 'array',
      targetGetUserTabsFields: ['id', 'title?', 'url?', 'lastOpened?', 'tabGroup?'],
      xwowGetUserTabsEnvelopeFields: ['success', 'limit', 'targetLimit', 'targetShape', 'filters', 'tabs', 'targetTabs'],
      targetGetUserHistorySourceApi: 'chrome.history.search',
      targetGetUserHistoryInputFields: ['query?', 'limit?', 'from?', 'to?'],
      targetGetUserHistoryDefaultLimit: 100,
      targetGetUserHistoryLimitBehavior: 'positive_integer_without_observed_upper_cap',
      targetGetUserHistoryOutputShape: 'array',
      targetGetUserHistoryFields: ['url', 'title?', 'dateVisited'],
      xwowGetUserHistoryEnvelopeFields: ['success', 'limit', 'targetShape', 'entries', 'history', 'targetHistory'],
      tabStateRepublish: true,
      finalizedTabBadges: true,
      approvalTokenPolicy: true,
      capabilityDiscovery: true,
      capabilityDiscoveryActions: ['browser.capabilities', 'capabilities.get', 'getCapabilities'],
      policyDecisionEvents: true,
      protocolSchemaVersion: BROWSER_PROTOCOL_SCHEMA_VERSION,
      nativeMethodSchemaCatalogVersion: NATIVE_METHOD_SCHEMA_CATALOG_VERSION,
      nativeMethodSchemas,
      nativeMethodSchemaConfirmedMethods: Object.keys(nativeMethodSchemas.methods),
      nativeMethodSchemaTargetEvidence: nativeMethodSchemas.targetEvidence,
      unsupportedCommandFallback: true,
      unsupportedCommandActions: ['executeUnhandledCommand', 'command.unsupported'],
      unsupportedCommandErrorCode: TARGET_UNSUPPORTED_COMMAND_ERROR_CODE,
      unsupportedCommandErrorField: 'unsupportedMethod',
      unsupportedCommandBrowserName: 'Chrome',
      unsupportedCommandFallbackFlow: ['route.started', 'browser_action:command.unsupported', 'route.failed'],
      targetUnsupportedCommandMessage: TARGET_UNSUPPORTED_COMMAND_MESSAGE_TEMPLATE,
      targetUnsupportedCommandActivatesSession: true,
      targetUnknownNativeMethodErrorCode: TARGET_UNKNOWN_NATIVE_METHOD_ERROR_CODE,
      targetUnknownNativeMethodErrorShape: 'jsonrpc_error_code_minus_1',
      xwowUnknownNativeMethodErrorCode: XWOW_UNKNOWN_NATIVE_METHOD_ERROR_CODE,
      xwowUnknownNativeMethodErrorShape: 'jsonrpc_method_not_found_minus_32601',
      approvalTokenPolicySource: 'xwow_action_time_extension',
      commandRouterEvents: true,
      lifecycleGuard: {
        pendingUpdateStorageKeys: ['xwowBrowserDataAiPendingUpdateVersion', 'codexPendingUpdateVersion'],
        targetPendingUpdateStorageKey: 'codexPendingUpdateVersion',
        targetPendingUpdateStorageArea: 'chrome.storage.session',
        targetUpdateListener: 'chrome.runtime.onUpdateAvailable',
        targetReloadGate: 'isBrowserControlActive',
        targetReloadWhenInactive: true,
        targetUpdateStateMachine: ['onUpdateAvailable', 'persistPendingUpdateVersion', 'ifActiveDeferReload', 'ifInactiveClearPendingAndReload'],
        xwowPendingUpdateMirrorKeys: ['xwowBrowserDataAiPendingUpdateVersion', 'codexPendingUpdateVersion'],
        heartbeatAlarms: ['xwow-browser-data-ai-client-heartbeat', 'client-heartbeat-alarm'],
        targetHeartbeatAlarm: 'client-heartbeat-alarm',
        targetHeartbeatPeriodMinutes: 0.5,
        heartbeatTimeoutMs: 3000,
        targetHeartbeatTimeoutMs: 3000,
        targetHeartbeatProbeMethod: 'ping',
        targetHeartbeatFailureOrder: ['stopActiveSessions', 'chrome.debugger.getTargets', 'detachTargetsWithTabId'],
        targetHeartbeatDetachScope: 'debugger_targets_with_tabId',
        clientHeartbeatStorageKeys: ['xwowBrowserDataAiClientHeartbeatState', 'codexClientHeartbeatState'],
        cleanupResultStorageKeys: ['xwowBrowserDataAiLifecycleCleanupResult', 'codexLifecycleCleanupResult'],
        cleanupResultFields: ['reason', 'stoppedSessionCount', 'stoppedSessions', 'detached', 'clientHeartbeat', 'recordedAt'],
        heartbeatFailureEventKinds: ['heartbeat_failure', 'debugger.detached.best_effort'],
        heartbeatFailureNativeEventMethod: 'onBrowserLifecycleEvent',
        heartbeatFailureAppEventRoute: '/events',
        heartbeatFailureAppEventTopLevelFields: ['type', 'nativeEventMethod', 'eventId', 'sessionId', 'turnId', 'eventType', 'kind', 'bridgeMethod', 'sourceKind', 'emittedAt', 'receivedAt', 'payload'],
        heartbeatFailureAppEventIndexedKind: 'heartbeat_failure',
        targetLifecycleReplayConfirmed: false,
        xwowHeartbeatEnhancements: ['clientHeartbeatState', 'cleanupResultPostmortem', 'lifecycleEventReplay', 'cdpLifecycleBestEffortDetachEvent'],
        clientHeartbeatStaleMs: 90000,
        clientHeartbeat: options.clientHeartbeat || null,
        extensionInstanceIdKey: 'extensionInstanceId',
        targetExtensionInstanceIdKey: 'extensionInstanceId',
      },
      lifecycleStatusSnapshot: true,
      lifecycleStatusActions: ['lifecycle.status', 'browser.lifecycleStatus', 'getLifecycleStatus'],
      sidePanelBootstrapGate: {
        storageKeys: ['xwowBrowserDataAiSidePanelOpenWindowIds', 'codexSidePanelOpenWindowIds'],
        targetStorageKey: 'codexSidePanelOpenWindowIds',
        targetStorageArea: 'chrome.storage.session',
        commandAliases: ['open-xwow-side-panel', 'open-codex-side-panel'],
        targetCommandAlias: 'open-codex-side-panel',
        messageAliases: ['ensure_xwow_app_server', 'ensure_codex_app_server', 'ensureCodexAppServer'],
        targetMessageAlias: 'ensure_codex_app_server',
        targetNativeMethod: 'ensureCodexAppServer',
        requiresOpenSidePanel: true,
        targetClosedError: 'Codex side panel is not open.',
        xwowClosedError: 'XWOW side panel is not open.',
        targetDeniedResponseFields: ['ok', 'error', 'nativeHostStatus', 'sidePanelOpen'],
        xwowDeniedResponseFields: ['ok', 'success', 'error', 'code', 'nativeHostStatus', 'sidePanelOpen', 'sidePanel'],
        targetOpenedEvent: 'chrome.sidePanel.onOpened',
        targetClosedEvent: 'chrome.sidePanel.onClosed',
        targetOpenApi: 'chrome.sidePanel.open',
        targetCloseApi: 'chrome.sidePanel.close',
        xwowEventKinds: ['status.restored', 'side_panel.opened', 'side_panel.closed', 'app_server_bootstrap.allowed', 'app_server_bootstrap.denied'],
        eventReplay: true,
      },
      sidePanelStatusSnapshot: true,
      sidePanelStatusActions: ['sidePanel.status', 'sidepanel.status', 'getSidePanelStatus'],
      sidePanelControl: true,
      sidePanelControlActions: ['sidePanel.open', 'sidePanel.close', 'sidePanel.toggle', 'openSidePanel', 'closeSidePanel', 'toggleSidePanel'],
      sidePanelEvents: true,
      downloadWait: true,
      downloadWaitActions: ['download.wait'],
      downloadWaitTargetFields: ['download_id', 'path', 'timeout_ms'],
      targetDownloadWaitInputFields: ['browser_id', 'tab_id', 'download_id', 'timeout_ms'],
      targetDownloadWaitOutputFields: ['path'],
      downloadStateSnapshot: true,
      downloadStateActions: ['download.state', 'downloads.state', 'getDownloadState'],
      targetDownloadChange: true,
      downloadChangeNativeMethod: 'onDownloadChange',
      targetDownloadNativeEventMethod: 'onDownloadChange',
      downloadChangeRequiresBrowserControl: true,
      targetDownloadCreatedListener: 'chrome.downloads.onCreated',
      targetDownloadChangedListener: 'chrome.downloads.onChanged',
      targetDownloadFilenameMap: 'downloadFilenamesById',
      targetDownloadUrlMap: 'downloadUrlsById',
      targetDownloadTrackedMap: 'targetDownloadTrackedById',
      targetDownloadCreatedGuards: ['integer_download_id', 'browser_control_active', 'filename_is_string'],
      targetDownloadChangedGuards: ['integer_download_id', 'target_tracked_download', 'known_filename', 'known_url', 'mapped_terminal_status'],
      targetDownloadChangedRequiresCurrentBrowserControlActive: false,
      targetDownloadCreatedStatus: 'started',
      targetDownloadStatusSource: 'DownloadDelta.state.current + DownloadDelta.error.current',
      targetDownloadStatusMapper: {
        complete: 'complete',
        interrupted_user_canceled: 'canceled',
        interrupted_other: 'failed',
        in_progress: 'in_progress_internal_only',
      },
      targetDownloadChangeFields: ['id', 'filename', 'url', 'status'],
      targetDownloadChangeStatuses: ['started', 'complete', 'canceled', 'failed'],
      xwowDownloadEnhancements: ['downloadStateSnapshot', 'downloadEventReplay', 'downloadContextBinding', 'downloadArtifactBinding', 'downloadSearch', 'downloadWaitById'],
      downloadArtifactBinding: true,
      downloadArtifactBindingSchemaVersion: 1,
      downloadContextState: true,
      policy: options.browserPolicy || null,
      nativeMessaging: permissions.includes('nativeMessaging'),
      nativeHostStatus: nativeStatus,
      nativeHostStatusKey: 'NATIVE_HOST_STATUS',
      targetNativeHostStatusKey: 'NATIVE_HOST_STATUS',
      targetNativeHostNames: {
        prod: 'com.openai.codexextension',
        internal: 'com.openai.codexextension.internal',
        dev: 'com.openai.codexextension.dev',
      },
      xwowNativeHostDefault: 'com.xwow.browser_data_ai',
      nativeRefreshStatus: true,
      nativeReconnectTimeout: true,
      nativeReconnectAlarm: true,
      targetNativeReconnectAlarmPrefix: 'native-transport-reconnect',
      targetNativeReconnectAlarmPattern: 'native-transport-reconnect:<application>',
      xwowNativeReconnectAlarmName: 'xwow-browser-data-ai-native-reconnect',
      xwowMirrorsTargetNativeReconnectAlarm: true,
      targetNativeReconnectDelayMs: 5000,
      targetNativeRequestIdPrefix: 'native-host:',
      targetNativeJsonRpcVersion: '2.0',
      targetNativeRequestEnvelopeFields: ['jsonrpc', 'id', 'method', 'params'],
      targetNativeResponseEnvelopeFields: ['jsonrpc', 'id', 'result|error'],
      targetNativeDisconnectedError: 'Native transport is disconnected; reconnect is pending',
      targetNativeInvalidResponseError: TARGET_NATIVE_INVALID_RESPONSE_ERROR,
      targetNativeResponseHandling: TARGET_NATIVE_RESPONSE_HANDLING,
      targetNativeResponseResolutionOrder: ['pending_id', 'error', 'result', 'invalid_response'],
      xwowNativeResponseValidation: XWOW_NATIVE_RESPONSE_VALIDATION,
      xwowNativeResponseJsonRpcRequired: true,
      targetUnknownNativeHandlerErrorCode: -1,
      targetNativeHandlerExceptionErrorCode: 1,
      targetNativeStatusMessageType: 'GET_NATIVE_HOST_STATUS',
      targetNativeBootstrapMessageType: 'ensure_codex_app_server',
      targetNativeBootstrapMethod: 'ensureCodexAppServer',
      targetNativeStatusRefreshBeforeReturn: true,
      xwowNativeStatusStorageKey: 'xwowBrowserDataAiNativeHostStatus',
      targetNativeTelemetryConfirmed: false,
      xwowNativeTelemetrySource: 'xwow_diagnostics_extension',
      xwowNativeTelemetryEvents: ['status_restored', 'status_refreshed', 'connect_started', 'connect_reused', 'connect_failed', 'connected', 'disconnect_requested', 'disconnected', 'reconnect_scheduled', 'reconnect_attempt', 'request_started', 'request_succeeded', 'request_failed', 'request_timeout'],
      nativeTransportEvents: true,
      browserEventSummary: true,
      browserEventSummaryActions: ['browser.events.summary', 'events.summary', 'getBrowserEventSummary'],
      browserEventReplaySources: ['browserEventBridgeLog', 'browserSessionEvents', 'downloadEvents', 'cdpEvents'],
      browserEventNativeMethods: ['onCDPEvent', 'onDownloadChange', 'onBrowserLifecycleEvent', 'onBrowserSessionEvent'],
      targetConfirmedEventSources: ['chrome.debugger.onEvent', 'chrome.downloads.onCreated', 'chrome.downloads.onChanged'],
      targetConfirmedNativeEventMethods: ['onCDPEvent', 'onDownloadChange'],
      targetEventSummaryConfirmed: false,
      xwowEventSummaryExtension: true,
      browserEventCheckpointFields: ['latestByEventType', 'latestBySourceKind', 'nextQuery.afterEventId', 'nextQuery.since'],
      browserEventNativeDeliveryFields: ['posted', 'success', 'pending', 'failed'],
      transport: nativeStatus.state === 'connected' ? 'nativeMessaging+local-http-command-poll' : 'local-http-command-poll',
      permissionInferredCapabilities: {
        downloadsUi: permissions.includes('downloads.ui'),
        notifications: permissions.includes('notifications'),
        downloadsUiActionConfirmed: false,
        notificationActionConfirmed: false,
        targetPermissionOnly: ['downloads.ui', 'notifications'],
        targetUnconfirmedActions: ['downloads.show', 'downloads.showDefaultFolder', 'notifications.create', 'notifications.clear'],
        xwowDoesNotExposePermissionOnlyActions: true,
        targetEvidence: 'manifest_permissions_without_confirmed_background_handlers',
      },
      activeSession: activeSession ? buildActiveSessionInfo(activeSession) : null,
      runtime: options.browserControlRuntime || null,
    },
    userState: {
      tabs: permissions.includes('tabs'),
      windows: permissions.includes('tabs'),
      history: permissions.includes('history'),
      bookmarks: permissions.includes('bookmarks'),
      topSites: permissions.includes('topSites'),
      readingList: permissions.includes('readingList'),
      sessions: permissions.includes('sessions'),
      tabFilters: ['platformDomain', 'storeName', 'recentActiveMs', 'lastOpenedAfter', 'tabGroup', 'query', 'urlIncludes', 'activeOnly'],
      tabFilterContract: 'xwow_operator_extension',
    },
    events: {
      cdp: true,
      cdpLifecycle: true,
      cdpCommand: true,
      pixelInput: true,
      download: true,
      downloadWaitLifecycle: true,
      contentInjection: true,
      policyDecision: true,
      sidePanel: true,
      browserVisibility: true,
      webMcp: true,
      fileChooser: true,
      nativeTransport: true,
      commandRouter: true,
      session: true,
      lifecycle: true,
      activeTabObserver: true,
      tabLifecycle: true,
      managedTabGroup: true,
      browserEventLog: true,
      browserEventSummary: true,
      browserEventCheckpointReplay: true,
      replayQuery: true,
    },
    permissions,
  };
}

export function buildPluginRegistrationPayload(options = {}) {
  const manifest = options.manifest || chrome.runtime.getManifest();
  const nativeStatus = options.nativeStatus || { state: 'unknown' };
  return {
    pluginId: options.pluginId || 'xwow-browser-data-ai',
    extensionId: chrome.runtime.id,
    displayName: manifest.name,
    version: manifest.version,
    capabilities: [...PLUGIN_CAPABILITIES],
    metadata: {
      manifestVersion: manifest.manifest_version,
      userAgent: navigator.userAgent,
      nativeHostName: options.nativeHostName || '',
      nativeHostStatus: nativeStatus.state || 'unknown',
      capabilitySchemaVersion: 1,
      capabilityContractSchemaVersion: CAPABILITY_CONTRACT_SCHEMA_VERSION,
    },
  };
}

export function buildCapabilityContracts() {
  const contracts = {};
  for (const capability of PLUGIN_CAPABILITIES) {
    contracts[capability] = CAPABILITY_CONTRACTS[capability] || capabilityContract(capability);
  }
  return contracts;
}

function capabilityContract(capability, options = {}) {
  return {
    capability,
    contractSchemaVersion: CAPABILITY_CONTRACT_SCHEMA_VERSION,
    inputSchemaVersion: Number(options.inputSchemaVersion || 1),
    outputSchemaVersion: Number(options.outputSchemaVersion || 1),
    actionClass: options.actionClass || 'observe',
    actions: options.actions || (options.action ? [options.action] : []),
    filters: options.filters || [],
    bindings: options.bindings || [],
    targetFacades: options.targetFacades || [],
    targetFields: options.targetFields || [],
    outputFields: options.outputFields || [],
    replaySources: options.replaySources || [],
    nativeEventMethods: options.nativeEventMethods || [],
    checkpointSchemaVersion: options.checkpointSchemaVersion || 0,
    checkpointFields: options.checkpointFields || [],
    nativeDeliveryFields: options.nativeDeliveryFields || [],
    replayPlan: options.replayPlan || [],
    targetBoundary: options.targetBoundary || '',
    summary: options.summary || '',
  };
}

function buildActiveSessionInfo(session) {
  return {
    sessionId: session.sessionId,
    turnId: session.turnId,
    currentTurnId: session.currentTurnId || null,
    activeTabId: session.activeTabId || null,
    ownedTabIds: Array.isArray(session.ownedTabIds) ? session.ownedTabIds : [],
    activeRequestCount: Number(session.activeRequestCount || 0),
    activeRequests: session.activeRequests || {},
  };
}
